#!/usr/bin/env python3
"""Stamp build information and export the current Pit Boss web release."""
import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import subprocess
from zoneinfo import ZoneInfo


def run_godot(command):
    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print(result.stdout, end="", flush=True)
    result.check_returncode()
    # Godot can report script errors while returning zero. Never label that a build success.
    if "SCRIPT ERROR:" in result.stdout or "ERROR:" in result.stdout:
        raise RuntimeError("Godot reported errors; export is not ready for manual verification")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--godot", default="godot", help="Godot binary with matching export templates")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--both", action="store_true", help="Build release and debug from one source/import/build timestamp")
    mode.add_argument("--debug", action="store_true", help="Export to casino-debug/ with developer tooling; leave casino/ unchanged")
    parser.add_argument("--version", default="0.5", help="Player-facing version")
    args = parser.parse_args()
    project = Path(__file__).resolve().parent
    # Fail before export rather than letting Godot fall back to its engine art.
    branding = project / "assets" / "pit_boss" / "branding"
    for name in ("pit_boss_chip.png", "pit_boss_logo.png", "pit_boss_splash.png"):
        asset = branding / name
        if not asset.is_file() or asset.read_bytes()[:8] != b"\x89PNG\r\n\x1a\n":
            raise RuntimeError(f"Missing or invalid source branding PNG: {asset}")
    updated = datetime.now(timezone.utc).astimezone(ZoneInfo("America/New_York"))
    timestamp = f"{updated:%B} {updated.day}, {updated.year} at {updated.hour % 12 or 12}:{updated:%M %p %Z}"
    metadata = (
        "# Generated by export_web.py; timestamp identifies the exported build.\n"
        "extends RefCounted\n\n"
        f"const VERSION := {json.dumps(args.version)}\n"
        f"const UPDATED_AT := {json.dumps(timestamp)}\n"
    )
    (project / "scripts" / "build_info.gd").write_text(metadata, encoding="utf-8")
    run_godot([args.godot, "--headless", "--path", str(project), "--editor", "--import", "--quit"])
    # Browser viewport synchronization is shared by wrapper and exported shell.
    destinations = ([project.parent / "casino-debug"] if args.debug else
                    [project.parent / "casino", project.parent / "casino-debug"] if args.both else
                    [project.parent / "casino"])
    html = (project / "web" / "index.html").read_text(encoding="utf-8")
    html, count = re.subn(r"(PIT BOSS <small>)[^<]*(</small>)", lambda match: match[1] + args.version + match[2], html, count=1)
    if count != 1:
        raise RuntimeError("Could not update the website version label")
    for destination in destinations:
        destination.mkdir(parents=True, exist_ok=True)
        (destination / "visible_viewport.js").write_text((project / "web" / "visible_viewport.js").read_text(encoding="utf-8"), encoding="utf-8")
        output = destination / "game.html"
        debug = destination.name == "casino-debug"
        run_godot([args.godot, "--headless", "--path", str(project),
                   "--export-debug" if debug else "--export-release", "Web", str(output)])
        # Godot derives game.icon.png from application/config/icon in the source
        # project. Both wrappers reuse that output, without a duplicate icon copy.
        (destination / "index.html").write_text(html, encoding="utf-8")
        if debug:
            print(f"Built Pit Boss {args.version} DEVELOPMENT. F10 enables tools. Output: {output}")
    print(f"Built Pit Boss {args.version}. Last updated {timestamp}")


if __name__ == "__main__":
    main()
