#!/usr/bin/env python3
"""Stamp build information and export the current Neon House web release."""
import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import subprocess
from zoneinfo import ZoneInfo


def run_godot(command):
    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    print(result.stdout, end="", flush=True)
    result.check_returncode()
    # Godot can report script errors while returning zero. Never label that a build success.
    if "SCRIPT ERROR:" in result.stdout or "ERROR:" in result.stdout:
        raise RuntimeError("Godot reported errors; export is not ready for manual verification")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--godot", default="godot", help="Godot binary with matching export templates")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--both", action="store_true", help="Build release and debug from one source/import/build timestamp")
    mode.add_argument("--debug", action="store_true", help="Export to casino-debug/ with developer tooling; leave casino/ unchanged")
    parser.add_argument("--version", default="0.4", help="Player-facing version")
    args = parser.parse_args()
    project = Path(__file__).resolve().parent
    updated = datetime.now(timezone.utc).astimezone(ZoneInfo("America/New_York"))
    timestamp = f"{updated:%B} {updated.day}, {updated.year} at {updated.hour % 12 or 12}:{updated:%M %p %Z}"
    metadata = (
        "# Generated by export_web.py; timestamp identifies the exported build.\n"
        "extends RefCounted\n\n"
        f"const VERSION := {json.dumps(args.version)}\n"
        f"const UPDATED_AT := {json.dumps(timestamp)}\n"
    )
    (project / "scripts" / "build_info.gd").write_text(metadata, encoding="utf-8")
    run_godot([args.godot, "--headless", "--path", str(project), "--editor", "--import", "--quit"])
    if args.debug or args.both:
        output = project.parent / "casino-debug" / "game.html"
        output.parent.mkdir(parents=True, exist_ok=True)
        run_godot([args.godot, "--headless", "--path", str(project), "--export-debug", "Web", str(output)])
        print(f"Built Neon House {args.version} DEVELOPMENT. F10 enables tools. Output: {output}")
        if args.debug:
            return
    run_godot([args.godot, "--headless", "--path", str(project), "--export-release", "Web"])
    wrapper = project.parent / "casino" / "index.html"
    html = (project / "web" / "index.html").read_text(encoding="utf-8")
    html, count = re.subn(r"(NEON HOUSE <small>)[^<]*(</small>)", lambda match: match[1] + args.version + match[2], html, count=1)
    if count != 1:
        raise RuntimeError("Could not update the website version label")
    wrapper.write_text(html, encoding="utf-8")
    print(f"Built Neon House {args.version}. Last updated {timestamp}")


if __name__ == "__main__":
    main()
