#!/usr/bin/env python3
"""Stamp build information and export the current Neon House web release."""
import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import subprocess
from zoneinfo import ZoneInfo


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--godot", default="godot", help="Godot binary with matching export templates")
    parser.add_argument("--version", default="0.3", help="Player-facing version")
    args = parser.parse_args()
    project = Path(__file__).resolve().parent
    updated = datetime.now(timezone.utc).astimezone(ZoneInfo("America/New_York"))
    timestamp = f"{updated:%B} {updated.day}, {updated.year} at {updated.hour % 12 or 12}:{updated:%M %p %Z}"
    metadata = (
        "# Generated by export_web.py; timestamp identifies the exported build.\n"
        "extends RefCounted\n\n"
        f"const VERSION := {json.dumps(args.version)}\n"
        f"const UPDATED_AT := {json.dumps(timestamp)}\n"
    )
    (project / "scripts" / "build_info.gd").write_text(metadata, encoding="utf-8")
    subprocess.run([args.godot, "--headless", "--path", str(project), "--editor", "--import", "--quit"], check=True)
    subprocess.run([args.godot, "--headless", "--path", str(project), "--export-release", "Web"], check=True)
    wrapper = project.parent / "casino" / "index.html"
    html = wrapper.read_text(encoding="utf-8")
    html, count = re.subn(r"(NEON HOUSE <small>)[^<]*(</small>)", lambda match: match[1] + args.version + match[2], html, count=1)
    if count != 1:
        raise RuntimeError("Could not update the website version label")
    wrapper.write_text(html, encoding="utf-8")
    print(f"Built Neon House {args.version}. Last updated {timestamp}")


if __name__ == "__main__":
    main()
