// Original educational practice items. Correct answer is stored separately so choices can be shuffled.
window.RECERT_CATEGORIES = [
  {id:"cardio",name:"Cardiovascular",weight:12,color:"#0d6b62"},
  {id:"derm",name:"Dermatologic",weight:5,color:"#dc745f"},
  {id:"endo",name:"Endocrine",weight:8,color:"#c89b46"},
  {id:"eent",name:"Eyes, Ears, Nose & Throat",weight:8,color:"#537f99"},
  {id:"gi",name:"Gastrointestinal & Nutrition",weight:10,color:"#7c9273"},
  {id:"gu",name:"Genitourinary",weight:5,color:"#af7e91"},
  {id:"heme",name:"Hematologic",weight:4,color:"#8b7767"},
  {id:"infectious",name:"Infectious Diseases",weight:7,color:"#4c9088"},
  {id:"msk",name:"Musculoskeletal",weight:8,color:"#cf885e"},
  {id:"neuro",name:"Neurologic",weight:5,color:"#6b81a5"},
  {id:"psych",name:"Psychiatry & Behavioral",weight:7,color:"#9e7770"},
  {id:"pulm",name:"Pulmonary",weight:10,color:"#558b79"},
  {id:"renal",name:"Renal",weight:4,color:"#a98a58"},
  {id:"repro",name:"Reproductive",weight:5,color:"#728a96"},
  {id:"emergent",name:"Legal, Ethical & DEI",weight:2,color:"#c26562"}
];

const q = (id, category, stem, correct, distractors, explanation, pearl, difficulty="core") => ({
  id, category, stem, correct, distractors, explanation, pearl, difficulty
});

window.RECERT_QUESTIONS = [
  q("cv01","cardio","A 64-year-old has crushing substernal chest pain and ST elevations in leads II, III, and aVF. Which coronary artery is most commonly involved?","Right coronary artery",["Left anterior descending artery","Left circumflex artery","Left main coronary artery"],"An inferior STEMI produces ST elevation in II, III, and aVF and most often reflects right coronary artery occlusion.","Inferior STEMI: II, III, aVF → usually RCA."),
  q("cv02","cardio","A stable patient has a regular narrow-complex tachycardia at 190/min that persists after vagal maneuvers. What is the next best treatment?","Rapid IV adenosine",["Synchronized cardioversion","IV amiodarone","Oral metoprolol and discharge"],"For stable regular narrow-complex SVT, adenosine is appropriate after vagal maneuvers fail. Instability would prompt synchronized cardioversion.","Stable SVT: vagal maneuvers, then adenosine."),
  q("cv03","cardio","A 72-year-old with atrial fibrillation develops sudden pain, pallor, paresthesia, and a pulseless left foot. What is the immediate management?","IV unfractionated heparin and urgent vascular evaluation",["Compression stockings","Oral aspirin with outpatient follow-up","Leg elevation and observation"],"The six Ps suggest acute limb ischemia. Immediate anticoagulation limits thrombus propagation while urgent revascularization is assessed.","Acute limb ischemia is a vascular emergency; anticoagulate promptly."),
  q("cv04","cardio","A patient has hypotension, jugular venous distention, and muffled heart sounds after a procedure. Which intervention is definitive?","Urgent pericardiocentesis",["IV furosemide","Needle thoracostomy","High-dose beta blockade"],"Beck triad after an invasive procedure suggests cardiac tamponade. Hemodynamically significant tamponade requires drainage.","Tamponade: hypotension + JVD + muffled heart sounds → drain."),

  q("de01","derm","A child has honey-colored crusted lesions around the nose and mouth without systemic illness. What is the most likely diagnosis?","Nonbullous impetigo",["Tinea corporis","Atopic dermatitis","Herpes zoster"],"Superficial erosions with honey-colored crust are classic for nonbullous impetigo, commonly caused by S. aureus or group A streptococcus.","Honey-colored crusts strongly suggest impetigo."),
  q("de02","derm","An older adult has a pearly papule with telangiectasias and a rolled border on the nose. What is the most likely diagnosis?","Basal cell carcinoma",["Squamous cell carcinoma","Melanoma","Actinic keratosis"],"Basal cell carcinoma commonly appears on sun-exposed skin as a pearly, translucent papule with telangiectasias and a rolled border.","Pearly + rolled border + telangiectasia → basal cell carcinoma."),
  q("de03","derm","A patient started lamotrigine two weeks ago and now has fever, mucosal erosions, and widespread tender targetoid lesions. What is the priority?","Stop the drug and arrange emergency hospitalization",["Continue the drug and add an antihistamine","Start topical antifungal therapy","Reassure and review in one week"],"Mucosal involvement and skin pain after a high-risk medication suggest Stevens-Johnson syndrome/toxic epidermal necrolysis, requiring immediate drug withdrawal and inpatient supportive care.","Suspected SJS/TEN: stop the culprit drug immediately."),
  q("de04","derm","A fluctuant, tender cutaneous abscess is present without systemic illness. What is the primary treatment?","Incision and drainage",["Topical corticosteroid","Oral antiviral therapy","Warm compresses alone in every case"],"Adequate incision and drainage is the key treatment for a drainable uncomplicated abscess; antibiotics depend on systemic features and patient risk.","A drainable abscess needs source control."),

  q("en01","endo","A patient with type 1 diabetes has abdominal pain, Kussmaul respirations, glucose 520 mg/dL, and an anion-gap acidosis. What is the first treatment priority?","Isotonic IV fluid resuscitation",["IV bicarbonate for every patient","Long-acting subcutaneous insulin","Fluid restriction"],"Initial DKA treatment begins with volume resuscitation. Potassium is checked and managed before or alongside IV insulin depending on its level.","DKA starts with fluids; potassium guides safe insulin timing."),
  q("en02","endo","A patient has weight loss, hyperpigmentation, hypotension, hyponatremia, and hyperkalemia. Which diagnosis is most likely?","Primary adrenal insufficiency",["Cushing syndrome","Primary hyperaldosteronism","SIADH"],"Primary adrenal failure causes cortisol and aldosterone deficiency, producing hypotension, hyponatremia, hyperkalemia, and increased ACTH-related hyperpigmentation.","Addison disease: low sodium, high potassium, hyperpigmentation."),
  q("en03","endo","A 68-year-old with new atrial fibrillation has weight loss, tremor, heat intolerance, and a suppressed TSH. What is the most likely underlying disorder?","Hyperthyroidism",["Hypothyroidism","Primary adrenal insufficiency","Hypoparathyroidism"],"Excess thyroid hormone can present subtly in older adults and is an important reversible trigger of atrial fibrillation.","New atrial fibrillation warrants consideration of thyroid disease."),
  q("en04","endo","A euvolemic patient has sodium 122 mEq/L, low serum osmolality, inappropriately concentrated urine, and no thyroid, adrenal, renal, or diuretic cause. What is most likely?","SIADH",["Diabetes insipidus","Primary hyperaldosteronism","Osmotic diuresis"],"Hypotonic euvolemic hyponatremia with urine that remains concentrated after exclusion of mimics is characteristic of SIADH.","SIADH retains water: low serum osmolality, concentrated urine."),

  q("ee01","eent","A patient has abrupt severe eye pain, halos, headache, nausea, a fixed mid-dilated pupil, and a cloudy cornea. What is the diagnosis?","Acute angle-closure glaucoma",["Open-angle glaucoma","Bacterial conjunctivitis","Retinal detachment"],"Acute angle closure causes rapid intraocular pressure elevation and is an ophthalmic emergency.","Painful red eye + fixed mid-dilated pupil = angle closure."),
  q("ee02","eent","A patient reports flashes, floaters, and a curtain descending over one eye. What is the next step?","Same-day ophthalmologic evaluation",["Routine optometry appointment","Topical antibiotic drops","Reassurance only"],"This symptom cluster suggests retinal detachment, which needs urgent assessment to preserve vision.","Flashes + floaters + curtain = retinal detachment until proven otherwise."),
  q("ee03","eent","A febrile child is drooling, sitting forward, and has inspiratory stridor with a muffled voice. What should be avoided?","Agitating the child with an oropharyngeal examination",["Calling airway specialists","Providing controlled oxygen","Preparing for a secured airway"],"Suspected epiglottitis demands a controlled airway approach. Throat manipulation may precipitate complete obstruction.","Epiglottitis: keep calm and secure the airway in a controlled setting."),
  q("ee04","eent","A patient has episodic vertigo lasting hours with fluctuating unilateral hearing loss, tinnitus, and aural fullness. What is most likely?","Meniere disease",["Benign paroxysmal positional vertigo","Vestibular neuritis","Acoustic trauma"],"The combination of episodic vertigo, fluctuating sensorineural hearing loss, tinnitus, and fullness is characteristic of Meniere disease.","Meniere disease couples vertigo with fluctuating auditory symptoms."),

  q("gi01","gi","A patient has fever, right upper quadrant pain, jaundice, hypotension, and confusion. What is the priority diagnosis?","Ascending cholangitis",["Uncomplicated biliary colic","Acute gastritis","Irritable bowel syndrome"],"Charcot triad plus hypotension and altered mental status is Reynolds pentad, indicating severe ascending cholangitis requiring antibiotics and urgent biliary drainage.","Reynolds pentad signals severe cholangitis and urgent source control."),
  q("gi02","gi","A patient with cirrhosis presents with large-volume hematemesis. Along with resuscitation and urgent endoscopy, which medication should be started?","Octreotide",["Oral omeprazole alone","Loperamide","Warfarin"],"Suspected variceal hemorrhage is treated with vasoactive therapy such as octreotide plus antibiotic prophylaxis and endoscopic control.","Variceal bleed: resuscitate, octreotide, antibiotics, urgent endoscopy."),
  q("gi03","gi","A patient has epigastric pain radiating to the back and a lipase more than three times normal. What is the cornerstone of initial management?","Supportive care with IV fluids and analgesia",["Routine prophylactic antibiotics","Immediate pancreatic surgery","Chronic glucocorticoids"],"Acute pancreatitis is generally managed initially with fluid resuscitation, pain control, and early nutrition as tolerated while the cause and severity are assessed.","Most acute pancreatitis begins with supportive care, not antibiotics."),
  q("gi04","gi","A patient has periumbilical pain that migrated to the right lower quadrant, anorexia, fever, and focal guarding. What diagnosis is most likely?","Acute appendicitis",["Acute pancreatitis","Cholelithiasis","Ulcerative colitis"],"Migration of visceral periumbilical pain to localized right lower quadrant pain with inflammatory signs is the classic appendicitis pattern.","Migratory periumbilical-to-RLQ pain is a high-yield appendicitis clue."),

  q("gu01","gu","A 16-year-old has sudden severe unilateral scrotal pain, nausea, a high-riding testis, and an absent cremasteric reflex. What is the next step?","Immediate surgical exploration",["Wait for a routine ultrasound appointment","Oral antibiotics and discharge","Needle aspiration"],"Testicular torsion is a time-sensitive surgical emergency. Strong clinical suspicion should not be delayed for imaging.","Torsion is a clinical emergency; do not delay detorsion for imaging."),
  q("gu02","gu","A patient has fever, flank pain, costovertebral angle tenderness, pyuria, and white blood cell casts. What is most likely?","Acute pyelonephritis",["Uncomplicated cystitis","Nephrotic syndrome","Urethritis"],"Systemic symptoms, flank pain, CVA tenderness, and WBC casts point to upper urinary tract infection.","WBC casts help localize infection to the kidney."),
  q("gu03","gu","An older man has urinary hesitancy, weak stream, nocturia, and a smooth enlarged prostate. What is the most likely diagnosis?","Benign prostatic hyperplasia",["Acute prostatitis","Prostate abscess","Testicular torsion"],"Progressive lower urinary tract symptoms with smooth symmetric enlargement are typical of BPH.","BPH classically causes obstructive lower urinary tract symptoms."),
  q("gu04","gu","A patient has severe colicky flank pain radiating to the groin with microscopic hematuria. He is afebrile and stable. What diagnosis is most likely?","Ureteral stone",["Acute appendicitis","Epididymitis","Glomerulonephritis"],"Intermittent severe flank-to-groin pain and hematuria are characteristic of ureterolithiasis.","Renal colic radiates from flank to groin and often causes hematuria."),

  q("he01","heme","A patient has fatigue, pica, microcytosis, low ferritin, high TIBC, and low transferrin saturation. What is the diagnosis?","Iron deficiency anemia",["Anemia of chronic inflammation","Vitamin B12 deficiency","Hereditary spherocytosis"],"Low iron stores with increased binding capacity and microcytosis are characteristic of iron deficiency.","Iron deficiency: ferritin down, TIBC up."),
  q("he02","heme","A patient has paresthesias, gait difficulty, macrocytosis, and hypersegmented neutrophils. Which deficiency is most concerning?","Vitamin B12 deficiency",["Iron deficiency","Vitamin K deficiency","Copper excess"],"B12 deficiency produces megaloblastic anemia and may cause irreversible neurologic injury if treatment is delayed.","Macrocytosis plus neurologic findings points to B12 deficiency."),
  q("he03","heme","A patient has isolated thrombocytopenia with petechiae after a viral illness. Hemoglobin, leukocytes, and coagulation tests are normal. What is most likely?","Immune thrombocytopenia",["Disseminated intravascular coagulation","Aplastic anemia","Hemophilia A"],"ITP commonly causes isolated immune-mediated platelet destruction without abnormalities in other cell lines or coagulation studies.","ITP is typically isolated thrombocytopenia."),
  q("he04","heme","A hospitalized patient has thrombocytopenia and a new DVT five days after starting heparin. What is the immediate action?","Stop all heparin and start a non-heparin anticoagulant",["Give platelet transfusion routinely","Continue heparin at a lower dose","Start warfarin alone immediately"],"Suspected heparin-induced thrombocytopenia is highly thrombotic. All heparin is stopped and alternative anticoagulation is started.","HIT causes thrombosis; stop heparin and anticoagulate another way."),

  q("in01","infectious","A hiker has fever, severe headache, thrombocytopenia, hyponatremia, and a rash beginning on wrists and ankles. What should be done?","Start doxycycline immediately",["Wait for serology before treatment","Give amoxicillin only","Use topical permethrin"],"Rocky Mountain spotted fever is treated empirically with doxycycline in all age groups because delay increases mortality.","Suspected RMSF: treat with doxycycline without waiting for tests."),
  q("in02","infectious","A patient has fever, a new murmur, splinter hemorrhages, and multiple positive blood cultures. What diagnosis is most likely?","Infective endocarditis",["Acute pericarditis","Viral myocarditis","Stable angina"],"Persistent bacteremia plus valvular and embolic/immunologic signs strongly suggests infective endocarditis.","Endocarditis links bacteremia, a murmur, and peripheral stigmata."),
  q("in03","infectious","A patient with fever and hypotension remains hypotensive after adequate crystalloid resuscitation. Which vasopressor is first line in septic shock?","Norepinephrine",["Dopamine for every patient","Phenylephrine for every patient","Oral midodrine"],"Norepinephrine is the preferred initial vasopressor for septic shock when hypotension persists despite fluids.","Septic shock after fluids: norepinephrine is first-line pressor."),
  q("in04","infectious","A patient has an expanding erythematous target-like rash after a tick bite in an endemic area. What is the most likely diagnosis?","Early localized Lyme disease",["Rocky Mountain spotted fever","Cellulitis from MRSA","Tinea versicolor"],"Erythema migrans is a clinical diagnosis of early Lyme disease and does not require positive serology before treatment.","Erythema migrans can diagnose early Lyme disease clinically."),

  q("ms01","msk","A patient has a hot swollen knee, fever, severe pain with passive range of motion, and a large effusion. What is the most important next test?","Urgent arthrocentesis",["Serum uric acid alone","Elective MRI","Bone density scan"],"Septic arthritis must be excluded urgently with synovial fluid cell count, Gram stain, culture, and crystal analysis.","Acutely hot monoarthritis needs joint aspiration."),
  q("ms02","msk","A patient has pain out of proportion after a tibial fracture, pain with passive stretch, and a tense compartment. What is the definitive treatment?","Emergency fasciotomy",["Tight circumferential casting","Outpatient physical therapy","Intra-articular steroid injection"],"Acute compartment syndrome threatens muscle and nerve viability and requires immediate pressure release.","Pain with passive stretch is an early compartment syndrome clue."),
  q("ms03","msk","An adolescent with obesity has hip pain referred to the knee and the affected leg rests externally rotated. What diagnosis is most likely?","Slipped capital femoral epiphysis",["Osgood-Schlatter disease","Septic bursitis","Achilles rupture"],"SCFE commonly occurs in adolescents with obesity and may present as hip, thigh, or knee pain with limited internal rotation.","Teen + obesity + hip/knee pain + external rotation → SCFE."),
  q("ms04","msk","A patient over age 50 has a new headache, jaw claudication, scalp tenderness, and transient visual symptoms. What should be started immediately?","High-dose glucocorticoids",["A triptan only","Oral antibiotics","Observation until biopsy results"],"Giant cell arteritis threatens irreversible vision loss. Treatment begins immediately; diagnostic confirmation should not delay steroids.","Suspected giant cell arteritis: protect vision with prompt steroids."),

  q("ne01","neuro","A patient develops sudden aphasia and right arm weakness 70 minutes ago. Noncontrast head CT shows no hemorrhage. What is the next priority?","Evaluate immediately for reperfusion therapy",["Wait 24 hours for MRI","Start a sedative and observe","Perform lumbar puncture first"],"An acute disabling ischemic stroke within the treatment window requires rapid assessment for IV thrombolysis and large-vessel occlusion therapy.","Time is brain: CT excludes hemorrhage, then assess reperfusion eligibility."),
  q("ne02","neuro","A patient has ascending weakness and areflexia two weeks after a diarrheal illness. What is the most likely diagnosis?","Guillain-Barré syndrome",["Myasthenia gravis","Parkinson disease","Bell palsy"],"Guillain-Barré causes acute symmetric ascending weakness with decreased reflexes, often after an infection.","Ascending weakness + areflexia = Guillain-Barré until proven otherwise."),
  q("ne03","neuro","A patient has low back pain, saddle anesthesia, urinary retention, and bilateral leg weakness. What is the next step?","Emergency MRI and surgical consultation",["Routine outpatient physical therapy","Oral muscle relaxant only","Elective nerve conduction study"],"Cauda equina syndrome requires immediate imaging and decompression to reduce permanent neurologic dysfunction.","Saddle anesthesia plus bladder dysfunction is a spinal emergency."),
  q("ne04","neuro","A generalized tonic-clonic seizure continues for more than five minutes. What is the first-line medication class?","A benzodiazepine",["An SSRI","A dopamine agonist","A beta blocker"],"Ongoing seizure activity at five minutes is status epilepticus; a benzodiazepine is given promptly before longer-acting antiseizure therapy.","Status epilepticus: benzodiazepine first."),

  q("ps01","psych","A patient reports depressed mood and loss of interest. Which question is the immediate safety priority?","Ask directly about suicidal thoughts, intent, plan, and access to means",["Ask only about family history","Defer risk assessment until the next visit","Avoid direct language to prevent suggesting suicide"],"Direct, specific suicide assessment is essential and does not increase suicidal behavior.","Ask directly about suicide; clarity improves safety."),
  q("ps02","psych","A patient has one week of decreased need for sleep, pressured speech, grandiosity, and risky behavior causing marked impairment. What is most likely?","A manic episode",["Generalized anxiety disorder","Persistent depressive disorder","Adjustment disorder"],"A week of abnormally elevated or irritable mood with increased energy and major impairment meets the core pattern of mania.","Decreased need for sleep is different from insomnia and is a mania clue."),
  q("ps03","psych","A patient taking an antipsychotic develops fever, severe rigidity, confusion, autonomic instability, and elevated creatine kinase. What is the diagnosis?","Neuroleptic malignant syndrome",["Serotonin syndrome","Panic attack","Acute dystonia only"],"Dopamine blockade can cause neuroleptic malignant syndrome with lead-pipe rigidity, hyperthermia, altered mental status, and autonomic instability.","NMS: antipsychotic exposure + rigidity + fever + autonomic instability."),
  q("ps04","psych","A patient taking serotonergic medications develops agitation, diaphoresis, diarrhea, hyperreflexia, and inducible clonus. What is most likely?","Serotonin syndrome",["Neuroleptic malignant syndrome","Malignant hyperthermia","Alcohol withdrawal only"],"Neuromuscular hyperactivity—especially clonus and hyperreflexia—helps distinguish serotonin toxicity from NMS.","Clonus and hyperreflexia are high-yield serotonin syndrome clues."),

  q("pu01","pulm","A patient with asthma has severe dyspnea, cannot speak full sentences, and has a nearly silent chest. What does the silent chest indicate?","Critically limited airflow and impending respiratory failure",["Mild disease with good air movement","Resolution of bronchospasm","A purely anxiety-related event"],"A quiet or silent chest during a severe asthma attack reflects minimal air movement and is an ominous sign.","In severe asthma, less wheeze can mean less airflow—not improvement."),
  q("pu02","pulm","A postoperative patient has sudden dyspnea, pleuritic chest pain, tachycardia, and hypoxemia. What diagnosis is most concerning?","Pulmonary embolism",["Acute bronchitis","Stable COPD","Chronic sinusitis"],"Recent surgery and acute cardiopulmonary symptoms create a high-risk presentation for pulmonary embolism.","Think PE with sudden dyspnea and pleuritic pain after immobilization or surgery."),
  q("pu03","pulm","A hypotensive trauma patient has severe respiratory distress, unilateral absent breath sounds, and distended neck veins. What is the immediate treatment?","Needle or finger thoracostomy followed by chest tube",["Wait for chest radiography","Start diuretics","Perform bronchoscopy first"],"Tension pneumothorax is diagnosed clinically in an unstable patient and decompressed immediately.","Unstable suspected tension pneumothorax: decompress before imaging."),
  q("pu04","pulm","A patient with COPD exacerbation has increased dyspnea, sputum volume, and sputum purulence. Which therapy is generally indicated in addition to bronchodilators and steroids?","Antibiotic therapy",["Long-term anticoagulation","Immediate lobectomy","Fluid restriction in every case"],"The three cardinal symptoms, especially purulence, identify an exacerbation likely to benefit from antibiotics.","COPD exacerbation with purulent sputum often warrants antibiotics."),

  q("re01","renal","A patient with vomiting and poor intake has rising creatinine, BUN:creatinine ratio above 20, and bland urine sediment. What is most likely?","Prerenal acute kidney injury",["Acute interstitial nephritis","Poststreptococcal glomerulonephritis","Obstructive nephropathy"],"Volume depletion reduces renal perfusion, leading to avid sodium and urea reabsorption and a prerenal pattern.","Hypovolemia + bland sediment + high BUN:Cr suggests prerenal AKI."),
  q("re02","renal","A patient has weakness, peaked T waves, and potassium 7.1 mEq/L. Which medication should be given first to stabilize the myocardium?","IV calcium",["Sodium polystyrene alone","Oral potassium","Hydrochlorothiazide only"],"IV calcium does not lower potassium but rapidly stabilizes cardiac membranes while potassium-shifting and removal therapies are arranged.","Hyperkalemia with ECG changes: calcium first for membrane stabilization."),
  q("re03","renal","A patient has edema, hypertension, cola-colored urine, red blood cell casts, and proteinuria after pharyngitis. What syndrome is present?","Nephritic syndrome",["Nephrotic syndrome","Prerenal azotemia","Diabetes insipidus"],"Hematuria with RBC casts, hypertension, and impaired renal function reflects glomerular inflammation—a nephritic pattern.","RBC casts are strongly suggestive of glomerulonephritis."),
  q("re04","renal","A patient with severe symptomatic hyponatremia has a seizure. Which initial therapy is appropriate?","Carefully monitored hypertonic saline",["Rapid unlimited free-water intake","Oral sodium restriction","A loop diuretic alone in every case"],"Seizure from severe hyponatremia requires prompt, controlled hypertonic saline with close monitoring to avoid overly rapid correction.","Symptomatic hyponatremia is treated urgently—but correction must be controlled."),

  q("rp01","repro","A patient with a positive pregnancy test has pelvic pain, vaginal bleeding, hypotension, and free pelvic fluid. What is the priority?","Emergency management of a ruptured ectopic pregnancy",["Routine prenatal follow-up","Oral contraception","Endometrial biopsy before stabilization"],"Shock, pregnancy, pain, bleeding, and free fluid indicate likely ruptured ectopic pregnancy requiring immediate resuscitation and surgical care.","Pregnancy + pain + shock = ruptured ectopic until proven otherwise."),
  q("rp02","repro","A pregnant patient at 35 weeks has new hypertension, proteinuria, severe headache, and visual symptoms. What condition is most likely?","Preeclampsia with severe features",["Chronic hypertension without complications","Normal pregnancy physiology","Hyperemesis gravidarum"],"New hypertension after 20 weeks with proteinuria and neurologic symptoms is preeclampsia with severe features.","Severe headache or visual symptoms can mark severe preeclampsia."),
  q("rp03","repro","A lactating patient has focal breast erythema, tenderness, fever, and flu-like symptoms without fluctuance. What is the recommended approach?","Continue breast emptying and treat for lactational mastitis",["Stop breastfeeding permanently","Immediate mastectomy","No treatment despite fever"],"Continued feeding or pumping helps drainage; appropriate antibiotics target common skin flora when bacterial mastitis is suspected.","Mastitis usually does not require stopping breastfeeding."),
  q("rp04","repro","A patient has sudden pelvic pain, nausea, an adnexal mass, and reduced ovarian blood flow. What is the next step?","Urgent gynecologic surgical evaluation",["Routine annual follow-up","Oral antibiotics only","Endometrial ablation"],"Ovarian torsion threatens ovarian viability and needs urgent operative assessment; imaging cannot safely exclude it when suspicion remains high.","Ovarian torsion is a time-sensitive surgical diagnosis."),

  q("et01","emergent","A competent adult refuses a recommended life-saving treatment after demonstrating understanding of the risks and alternatives. What principle applies?","Respect the informed refusal",["Treat over objection in every case","Ask the family to override the patient","Declare incapacity solely because the choice is risky"],"A patient with decision-making capacity may refuse treatment, even when the decision may lead to serious harm.","Capacity is about the decision process, not whether clinicians agree with the choice."),
  q("et02","emergent","A clinician suspects child abuse based on concerning injuries and an inconsistent history. What is the clinician's duty?","Report reasonable suspicion to the appropriate protective authority",["Prove abuse before reporting","Confront the suspected abuser alone first","Wait for the next visit"],"Mandated reporters generally report reasonable suspicion; investigation is the role of protective services, not the reporting clinician.","Report suspicion—do not wait to prove abuse."),
  q("et03","emergent","A patient with limited English proficiency needs consent for a complex procedure. What is the best approach?","Use a qualified medical interpreter",["Use a young child in the family","Rely on gestures only","Ask the patient to sign an English form without interpretation"],"A qualified interpreter supports accurate communication, valid consent, confidentiality, and patient autonomy.","Qualified interpreters are central to safe, equitable informed consent."),
  q("et04","emergent","An unconscious patient with no surrogate needs immediate surgery to prevent death. No advance directive is available. What permits treatment?","The emergency exception to informed consent",["A social media poll","Consent from any hospital visitor","No treatment until a court order arrives"],"When delay threatens life and preferences are unknown, necessary emergency treatment may proceed under presumed consent.","Emergency care may proceed when delay is dangerous and wishes are unknown.")
];
